services:
  postgres:
    container_name: namaskar-postgres-sql
    hostname: postgres-sql
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres-password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: namaskar
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata  
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - namaskar
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - namaskar
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  namaskar:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local