export const EmojiMap = {
  "💖": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/2764_fe0f/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/2764_fe0f/512.gif"
        alt="💖"
        width="32"
        height="32"
      />
    </picture>
  ),
  "👍": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f44d/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f44d/512.gif"
        alt="👍"
        width="32"
        height="32"
      />
    </picture>
  ),
  "🎉": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f389/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f389/512.gif"
        alt="🎉"
        width="32"
        height="32"
      />
    </picture>
  ),
  "👏": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f44f/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f44f/512.gif"
        alt="👏"
        width="32"
        height="32"
      />
    </picture>
  ),
  "😂": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f602/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f602/512.gif"
        alt="😂"
        width="32"
        height="32"
      />
    </picture>
  ),
  "😯": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f62f/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f62f/512.gif"
        alt="😯"
        width="32"
        height="32"
      />
    </picture>
  ),
  "😥": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f613/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f613/512.gif"
        alt="😥"
        width="32"
        height="32"
      />
    </picture>
  ),
  "🤔": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f914/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f914/512.gif"
        alt="🤔"
        width="32"
        height="32"
      />
    </picture>
  ),
  "👎": (
    <picture>
      <source
        srcSet="https://fonts.gstatic.com/s/e/notoemoji/latest/1f44e/512.webp"
        type="image/webp"
      />
      <img
        src="https://fonts.gstatic.com/s/e/notoemoji/latest/1f44e/512.gif"
        alt="👎"
        width="32"
        height="32"
      />
    </picture>
  ),
};
